export const LOAD_MOVIE_LIST_SUCCESS = "LOAD_MOVIE_LIST_SUCCESS";
export const LOAD_MOVIE_LIST_START = "LOAD_MOVIE_LIST_START";
export const DELETE_MOVIE_LIST_SUCCESS = "DELETE_MOVIE_LIST_SUCCESS";
export const EDIT_MOVIE = 'EDIT_MOVIE';
export const SORT_MOVIES = 'SORT_MOVIES';