export const LOAD_MOVIE_LIST_SUCCESS = "LOAD_MOVIE_LIST_SUCCESS";
export const DELETE_MOVIE = "DELETE_MOVIE";
export const EDIT_MOVIE = "EDIT_MOVIE";
export const SORT_MOVIES = "SORT_MOVIES";
export const FILTER_MOVIES = "FILTER_MOVIES";
export const ADD_MOVIE = "ADD_MOVIE";
export const LOAD_MOVIE_DETAILS = "LOAD_MOVIE_DETAILS";